name = "otel-test"
main = "src/index.ts"
compatibility_date = "2023-03-27"
compatibility_flags = [ "nodejs_compat" ]

kv_namespaces = [
  # { binding = "OTEL_TEST", id = "f124c9696873443da0a277ddb75000ca", preview_id = "3569aab8617645d9b8ed4bd1d45c8d96" }
  { binding = "OTEL_TEST", id = "b47e660f2c1940329adf9a7aa2d93804", preview_id = "9fb9bceb46064170adadcefb7f801810" }
]

[durable_objects]
bindings = [
  { name = "Test_Otel_DO", class_name = "TestOtelDO" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["TestOtelDO"]