name = "otel-test"
main = "src/index.ts"
compatibility_date = "2023-03-27"
compatibility_flags = [ "nodejs_compat", "nodejs_zlib ]

kv_namespaces = [
  { binding = "OTEL_TEST", id = "f124c9696873443da0a277ddb75000ca", preview_id = "3569aab8617645d9b8ed4bd1d45c8d96" }
]

[durable_objects]
bindings = [
  { name = "Test_Otel_DO", class_name = "TestOtelDO" }
]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["TestOtelDO"]
